
const productData = [
    {
        id: 1,
        title: "Свежие помидоры",
        category: "Паслёновые",
        origin: "Астраханская область",
        year: 2024,
        description: "Сочные красные помидоры, выращенные в открытом грунте под южным солнцем. Идеальны для салатов, соусов и консервации. Содержат ликопин, витамины A, C и K.",
 
        price: 189,
        unit: "кг",
        image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop",
    },
    {
        id: 2,
        title: "Морковь сладкая",
        category: "Корнеплоды",
        origin: "Московская область",
        year: 2024,
        description: "Хрустящая сладкая морковь с высоким содержанием бета-каротина. Отлично подходит для свежих салатов, соков и приготовления горячих блюд. Укрепляет зрение и иммунитет.",
      
        price: 89,
        unit: "кг",
        image: "https://bmb-holding.uz/wp-content/uploads/2025/01/volga-1-1.jpg",
    },
    {
        id: 3,
        title: "Огурцы грунтовые",
        category: "Тыквенные",
        origin: "Краснодарский край",
        year: 2024,
        description: "Свежие хрустящие огурцы с тонкой кожицей. Богаты водой, калием и витаминами. Идеальны для летних салатов, окрошки и маринования.",
     
        price: 129,
        unit: "кг",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4Gx7P2ySdBDg8qE-9Um7xj6_sOUnpOD0eHg&s",
    },
    {
        id: 4,
        title: "Картофель молодой",
        category: "Корнеплоды",
        origin: "Белгородская область",
        year: 2024,
        description: "Молодой картофель с нежной кожицей и сладковатым вкусом. Богат крахмалом, витамином C и калием. Отлично подходит для варки, запекания и приготовления пюре.",
   
        price: 79,
        unit: "кг",
        image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&auto=format&fit=crop",
    },
    {
        id: 5,
        title: "Капуста белокочанная",
        category: "Крестоцветные",
        origin: "Ленинградская область",
        year: 2024,
        description: "Плотные кочаны капусты с сочными хрустящими листьями. Источник витамина C, клетчатки и антиоксидантов. Подходит для салатов, тушения и квашения.",
    
        price: 65,
        unit: "кг",
        image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop",
    },
    {
        id: 6,
        title: "Болгарский перец",
        category: "Паслёновые",
        origin: "Волгоградская область",
        year: 2024,
        description: "Сладкий разноцветный перец: красный, жёлтый и зелёный. Богат витамином C, A и антиоксидантами. Отлично подходит для фаршировки, салатов и запекания.",
        
        price: 249,
        unit: "кг",
        image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800&auto=format&fit=crop",
    },
    {
        id: 7,
        title: "Лук репчатый",
        category: "Луковые",
        origin: "Ростовская область",
        year: 2024,
        description: "Крепкие золотистые луковицы с острым вкусом и характерным ароматом. Обладает антибактериальными свойствами, богат витаминами и минералами.",
       
        price: 55,
        unit: "кг",
        image: "https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?w=800&auto=format&fit=crop",
    },
    {
        id: 8,
        title: "Чеснок свежий",
        category: "Луковые",
        origin: "Ставропольский край",
        year: 2024,
        description: "Ароматный чеснок с крупными зубчиками. Природный антибиотик, укрепляет иммунитет и улучшает пищеварение. Идеален для соусов, маринадов и приправ.",
   
        price: 320,
        unit: "кг",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtU51sLFmPHPgIoAXtdZoJZCgWnF5M-s2LAw&s",
    },
    {
        id: 9,
        title: "Баклажаны",
        category: "Паслёновые",
        origin: "Крым",
        year: 2024,
        description: "Тёмно-фиолетовые баклажаны с нежной мякотью. Богаты клетчаткой, антиоксидантами и калием. Отлично подходят для запекания, рагу и икры.",
    
        price: 199,
        unit: "кг",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHj77dp6PetgeEiQOHjPRgRRLA5GkhfUmS8Q&s",
    },
    {
        id: 10,
        title: "Кабачки цукини",
        category: "Тыквенные",
        origin: "Воронежская область",
        year: 2024,
        description: "Молодые нежные кабачки с тонкой кожицей. Низкокалорийные, богаты витаминами и минералами. Идеальны для жарки, тушения и приготовления оладий.",
        
        price: 119,
        unit: "кг",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2Zsa6IDRb2rNgnzSFj1JylBnRJ76OM-F5dQ&s",
    },
    {
        id: 11,
        title: "Свёкла столовая",
        category: "Корнеплоды",
        origin: "Тамбовская область",
        year: 2024,
        description: "Сладкая сочная свёкла с насыщенным бордовым цветом. Богата железом, фолиевой кислотой и антиоксидантами. Подходит для борщей, салатов и запекания.",
        price: 75,
        unit: "кг",
        image: "https://i0.wp.com/potatosystem.ru/wp-content/uploads/2023/07/sv1.jpg?resize=1140%2C570&ssl=1",
    },
    {
        id: 12,
        title: "Редис весенний",
        category: "Крестоцветные",
        origin: "Подмосковье",
        year: 2024,
        description: "Острый хрустящий редис с ярким вкусом. Богат витамином C, клетчатки и эфирными маслами. Отлично дополняет весенние салаты и окрошку.",
        rating: 8.2,
        price: 149,
        unit: "кг",
        image: "https://www.rbc.ua/static/img/0/b/0bb2d4215d5de184c10e9f50ee1d9553_m_11d1c55f944d2c6a5a511b4abde4b402_480x270.jpg",
    },
];

export default productData;
